"""
Top-level package for ECG generation experiments.
"""

try:
    from ecgen._version import __version__  # generated by setuptools-scm at build/install time
except ImportError:  # source tree without an install (e.g. PYTHONPATH usage)
    __version__ = "0.0.0+unknown"

from ecgen.generate import generate
from ecgen.plot import plot_ecg

__all__ = ["data", "f", "generate", "models", "plot_ecg", "training", "evaluation", "utils"]
